version: 2
updates:
  - package-ecosystem: "nuget" # See documentation for possible values
    directory: "/AutoTests.Framework/" # Location of package manifests
    schedule:
      interval: "daily"
    open-pull-requests-limit: 1
