on:
  workflow_dispatch:
    inputs:
      version:
        description: "Nuget package version"
        required: true
        type: string

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Setup .NET
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: 6.0.x
    
      - name: Check out repository
        uses: actions/checkout@v3

      - name: pack
        run: dotnet pack ./AutoTests.Framework/AutoTests.Framework.sln -p:Configuration=Release -p:Version=${{ inputs.Version }} -o "./build"

      - name: push to nuget
        run: dotnet nuget push ./build/*.nupkg -k ${{ secrets.NUGET }} -s https://api.nuget.org/v3/index.json
