on:
  workflow_dispatch:
    inputs:
      version:
        description: "Nuget package version"
        required: true
        type: string
run-name: Release ${{ inputs.Version }}

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 8.0.x

      - name: Check out repository
        uses: actions/checkout@v4

      - name: Pack
        run: dotnet pack -c Release -p:Version=${{ inputs.Version }} -o "./build" ./src/AutoTests.Framework.sln

      - name: Push to Nuget
        run: dotnet nuget push ./build/*.nupkg -k ${{ secrets.NUGET }} -s https://api.nuget.org/v3/index.json
