on:
  workflow_dispatch:
    inputs:
      version:
        description: "Nuget package version"
        required: true
        type: string
        default: "5.3.x"

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: 7.0.x

      - name: Check out repository
        uses: actions/checkout@v3

      - name: Pack
        run: dotnet pack -c Release -p:Version=${{ inputs.Version }} -o "./build" ./src/AutoTests.Framework.sln

      - name: Push to Nuget
        run: dotnet nuget push .\build\*.nupkg -k ${{ secrets.NUGET }} -s https://api.nuget.org/v3/index.json
